apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vi3c19gmi-go
  janus-idp.io/tekton: vi3c19gmi-go
  backstage.io/kubernetes-id: vi3c19gmi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vi3c19gmi-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
