apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vi3c19gmi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vi3c19gmi-go 
  name: vi3c19gmi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vi3c19gmi-go 
