apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vi3c19gmi-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-go:b90d466dc243a272decc2700067321d309ffd5bb@sha256:2559c421fbac0cbd28b89d123605a9fafb1bcea3437ed410028a6b5d61689391
          name: container-image
