apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vi3c19gmi-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-go:a874a2b7b43790bbdfbe62402ef26ac70f1dcd74@sha256:ec43637cc8ee696fb02e4fb67bdaab3e2656f6c1eca7bde7c12c8f89491bc774
          name: container-image
